name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Test and build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node 18
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install Dependencies
        run: npm ci

      - name: Test
        run: npm run test:coverage

      - name: Coveralls
        uses: coverallsapp/github-action@v2
        with:
          format: lcov
          file: "./coverage/lcov.info"

      - name: Build
        run: npm pack
